server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: account-service
              uri: http://localhost:8082
              predicates:
                - Path=/accounts/**,/Profile/**,/admin/accounts/**


            - id: Auth-Service
              uri: http://localhost:8081
              predicates:
                - Path=/Auth/**,/admin/auth/**
            - id: Transaction-services
              uri: http://localhost:8083
              predicates:
                - Path=/payment-transactions/**
