server:
  port: 8080

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: bank-redis
      port: 6379


  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: account-service
              uri: http://account-service:8082
              predicates:
                - Path=/accounts/**,/profile/**,/admin/accounts/**,/admin/profiles/**
              filters:
                - addUserHeaders
                - RateLimiter
            - id : auth-public
              uri: http://auth-service:8081
              predicates:
                - Path=/Auth/login,/Auth/register,/Auth/refresh,/Auth/logout

            - id : auth-admin
              uri: http://auth-service:8081
              predicates:
                - Path=/admin/auth/**
              filters:
                - addUserHeaders
                - RateLimiter

            - id: Transaction-services
              uri: http://transaction-service:8083
              predicates:
                - Path=/payment-transactions/**
              filters:
                - addUserHeaders
                - RateLimiter


jwt:
  secret: Kp7q8Hf9m1Yv0M0RrXl+TtqUO9sA3R6c2ZkFJm1P3S0=
  access-token-expiration: 900000
  refresh-token-expiration: 604800000
