spring:
  application:
    name: Auth-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/Auth_database
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: Kp7q8Hf9m1Yv0M0RrXl+TtqUO9sA3R6c2ZkFJm1P3S0=
  access-expiry-ms: 900000