package com.siddu.Enums;

public enum TransferErrorCode {
    SENDER_ACCOUNT_NOT_FOUND,
    RECEIVER_ACCOUNT_NOT_FOUND,
    ACCESS_DENIED,
    SENDER_ACCOUNT_INACTIVE,
    RECEIVER_ACCOUNT_INACTIVE,
    INSUFFICIENT_BALANCE,
    INVALID_PIN,
    SAME_ACCOUNT,
    SUCCESS,
    CONCURRENT_TRANSACTION
}